name: gnr-stitching
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - opencv::opencv=4.8.1
  - pillow=10.0.0
  - pandas=2.0.3
  - pip:
    - easyocr==1.7.0
    - rapidfuzz==3.1.1
